keyconfig_version = (3, 6, 13)
keyconfig_data = \
[("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("ah.clickbypassview", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("view3d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.zoom", {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.rotate", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("bagapie.duplicatelinkedgroup", {"type": 'N', "value": 'PRESS', "alt": True}, None),
    ("bagapie.duplicategroup", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'J', "value": 'PRESS'},
     {"properties":
      [("name", 'BAGAPIE_MT_pie_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_materialutilities_main'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'UVTOOLKIT_MT_pie_3dview'),
       ],
      },
     ),
    ("cbl.convert_between",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("cbl.apply_mirror",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("cbl.drop_cable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_remove_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_apply_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_single_vert",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_add_circle",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_profile_bundle",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_find_profile",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("cbl.insulate",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("cbl.simulate_cable_dialog",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplitrecable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplit",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_geocable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_segment",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_connector",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorconnect",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_edit_cable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_selected",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_edge",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("cbl.massive_cables",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratordraw",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_cablerator'),
       ],
      },
     ),
    ("qremesher.remesh", {"type": 'R', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.cursor3d",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {    "active":False,
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'MOUSESMARTZOOM', "value": 'ANY'}, None),
    ("view3d.localview_remove_from", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.localview_remove_from", {"type": 'SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'NORTH'},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'SOUTH'},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'EAST'},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'WEST'},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CW', "value": 'PRESS'},
     {"properties":
      [("angle", 1.5707964),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("angle", -1.5707964),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_ex_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", 0.5235988),
       ("orient_axis", 'Z'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", -0.5235988),
       ("orient_axis", 'Z'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", 0.5235988),
       ("orient_axis", 'X'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", -0.5235988),
       ("orient_axis", 'X'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", -0.5235988),
       ("orient_axis", 'Y'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("value", 0.5235988),
       ("orient_axis", 'Y'),
       ("orient_type", 'LOCAL'),
       ("release_confirm", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Armature",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("armature.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("armature.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("armature.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("armature.align", {"type": 'A', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("armature.calculate_roll", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("armature.roll_clear", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("armature.switch_direction", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("armature.bone_primitive_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("armature.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("armature.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("armature.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("armature.select_mirror",
     {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("armature.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("armature.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("armature.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("armature.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("armature.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("armature.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("armature.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("armature.shortest_path_pick", {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_armature_delete'),
       ],
      },
     ),
    ("armature.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("armature.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("armature.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("armature.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("armature.extrude_forked", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("armature.click_extrude", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("armature.fill", {"type": 'F', "value": 'PRESS'}, None),
    ("armature.split",
     {"type": 'Y', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("armature.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_toggle'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_enable'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_bone_options_disable'),
       ],
      },
     ),
    ("armature.layers_show_all", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("armature.armature_layers", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("armature.bone_layers", {"type": 'M', "value": 'PRESS'}, None),
    ("transform.bbone_resize", {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'BONE_ENVELOPE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'BONE_ROLL'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_armature_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_armature_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Curve",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("cbl.cut_cable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_add_point",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_unrotate",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_switch_handle",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {    "active":False,
      },
     ),
    ("cbl.one_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_add_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'TOPBAR_MT_edit_curve_add'),
       ],
      },
     ),
    ("curve.handle_type_set", {"type": 'V', "value": 'PRESS'}, None),
    ("curve.vertex_add", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_row", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("curve.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("curve.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("curve.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("curve.shortest_path_pick", {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("curve.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("curve.split",
     {"type": 'Y', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("curve.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("curve.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("curve.make_segment", {"type": 'F', "value": 'PRESS'}, None),
    ("curve.cyclic_toggle", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("curve.dissolve_verts", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("curve.dissolve_verts", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("curve.tilt_clear", {"type": 'T', "value": 'PRESS', "alt": True}, None),
    ("transform.tilt", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'CURVE_SHRINKFATTEN'),
       ],
      },
     ),
    ("curve.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("curve.normals_make_consistent", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("mesh.f2", {"type": 'F', "value": 'PRESS'}, None),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("affect", 'EDGES'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("affect", 'VERTICES'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("mesh.loop_select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select", {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("mesh.edgering_select",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_split'),
       ],
      },
     ),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS', "repeat": True}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split",
     {"type": 'Y', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_occlude_geometry", False),
       ("only_selected", True),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_normals'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Outliner",
  {"space_type": 'OUTLINER', "region_type": 'WINDOW'},
  {"items":
   [("ah.clickbypass", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("outliner.highlight_update", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("outliner.item_rename",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("use_active", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("tweak", True),
       ("mode", 'ADD'),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.operation", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_view_pie'),
       ],
      },
     ),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True}, None),
    ("outliner.show_hierarchy", {"type": 'HOME', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'PERIOD', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("outliner.scroll_page",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", False),
       ],
      },
     ),
    ("outliner.scroll_page",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", True),
       ],
      },
     ),
    ("outliner.show_one_level", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("outliner.show_one_level",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.expanded_toggle", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("outliner.keyingset_add_selected", {"type": 'K', "value": 'PRESS'}, None),
    ("outliner.keyingset_remove_selected", {"type": 'K', "value": 'PRESS', "alt": True}, None),
    ("anim.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("outliner.collection_new", {"type": 'C', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("outliner.collection_exclude_set", {"type": 'E', "value": 'PRESS'}, None),
    ("outliner.collection_exclude_clear", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("outliner.hide", {"type": 'H', "value": 'PRESS'}, None),
    ("outliner.unhide_all", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("outliner.id_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.id_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
